### ISSUE TITLE
Add redirect field

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#131]
**What problem are we trying to solve?**
If a source has been deprecated because a new one is available, users need to be able to identify the replacement source.

**How do we know when this is done?**

- The schema includes a redirect array field that is optional. Array so that we can capture feeds that have been split (aggregate that's now a variety of feeds).
- Array has an associated comment

- redirect
   - comment

- Tasks
   - Modify catalog schema
      - Add optional field : redirect
      - Field can contain multiple redirect IDs. 
   - Modify csv file creation script
      - Take into account the optional added field
   - In mobility-feed-api repo, modify the script that populates the DB. 
      - I believe the field is already present in the DB schema.

Reference
[- Here's a list of examples of feeds that need a redirect defined](https://docs.google.com/spreadsheets/d/1MTEghrCFUixbHhH9Cqd-7htpnwkAN1f8UEpUoa098Sg/edit?usp=sharing). You can pick one to update the CSV action.

**Comment by e-lo** [comment]
Suggestion:

```yaml
redirect:
 - 1234 # comments helpful here; i.e. feed split into two separate feeds
 - 1235 # make a list in case there are multiple
last_updated: <auto-filled last updated date>  # sometimes recently deprecated feeds still have "ok" data in them
deprecated: true
```
